### ISSUE TITLE
not able to register 

### ISSUE THREAD

**Issue by vigneshwarants** [3bytessolutions/CallService-sample#6]
sample application form github but the register is not working the parameters like

CallService.getDefaultInstance().register(userId, GOOGLE_CLOUD_PROJECT_ID, MainActivity.this, new CallService.Callback() {
    @Override
    public void onError(Exception error) {
	     // something went wrong
	}
	@Override
    public void onSuccess() {
	    // done, you can make/receive call now
	} 
});

but from in library 

public void register(String var1, String var2, String var3, Context var4, CallService.Callback var5) {
    z var6 = new z(this, var4, var1, var3, var2, var5);
    var6.execute(new Void[0]);
}
it have one more parameter like (var3) so i cant to register. can please explain me , then what type of data should pass on var3.

**Comment by 3bytessolutions** [comment]
there's a String param between var1 and var2, need to pass user's display
name there.

**Comment by vigneshwarants** [comment]
ok . so can i pass the user's name to var2?

**Comment by vigneshwarants** [comment]
now i am trying to register but its shows the failed to register and shows exception java.io.IOException: INVALID_SENDER.

**Comment by 3bytessolutions** [comment]
your client is not authorized to call our backend. send us details
mentioned in README and we'll authorize it.

**Comment by vigneshwarants** [comment]
now i am getting these exception how i can solve these ??

com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAuthIOException

**Comment by alispoject** [comment]
m getting 
W/AbstractGoogleClient: Application name is not set. Call Builder#setApplicationName.
10-27 12:37:52.712 18332-18332/com.threebytes.callservicesample W/System.err: com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAuthIOException
10-27 12:37:52.712 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:286)
10-27 12:37:52.712 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
10-27 12:37:52.712 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
10-27 12:37:52.712 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at com.threebytes.callapi.z.a(Unknown Source)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at com.threebytes.callapi.z.doInBackground(Unknown Source)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err:     at java.lang.Thread.run(Thread.java:761)
10-27 12:37:52.713 18332-18332/com.threebytes.callservicesample W/System.err: Caused by: com.google.android.gms.auth.GoogleAuthException: INVALID_AUDIENCE
10-27 12:37:52.714 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.zza(Unknown Source)
10-27 12:37:52.714 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
10-27 12:37:52.714 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
10-27 12:37:52.714 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
10-27 12:37:52.714 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
10-27 12:37:52.714 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
10-27 12:37:52.714 18332-18332/com.threebytes.callservicesample W/System.err: 	... 12 more
10-27 12:37:58.876 18332-18357/com.threebytes.callservicesample W/AbstractGoogleClient: Application name is not set. Call Builder#setApplicationName.
10-27 12:37:59.646 18332-18332/com.threebytes.callservicesample W/System.err: com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAuthIOException
10-27 12:37:59.646 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:286)
10-27 12:37:59.646 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
10-27 12:37:59.646 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
10-27 12:37:59.647 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
10-27 12:37:59.647 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
10-27 12:37:59.647 18332-18332/com.threebytes.callservicesample W/System.err:     at com.threebytes.callapi.z.a(Unknown Source)
10-27 12:37:59.647 18332-18332/com.threebytes.callservicesample W/System.err:     at com.threebytes.callapi.z.doInBackground(Unknown Source)
10-27 12:37:59.647 18332-18332/com.threebytes.callservicesample W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
10-27 12:37:59.647 18332-18332/com.threebytes.callservicesample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-27 12:37:59.647 18332-18332/com.threebytes.callservicesample W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
10-27 12:37:59.648 18332-18332/com.threebytes.callservicesample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-27 12:37:59.648 18332-18332/com.threebytes.callservicesample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-27 12:37:59.648 18332-18332/com.threebytes.callservicesample W/System.err:     at java.lang.Thread.run(Thread.java:761)
10-27 12:37:59.648 18332-18332/com.threebytes.callservicesample W/System.err: Caused by: com.google.android.gms.auth.GoogleAuthException: INVALID_AUDIENCE
10-27 12:37:59.649 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.zza(Unknown Source)
10-27 12:37:59.649 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
10-27 12:37:59.649 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
10-27 12:37:59.649 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
10-27 12:37:59.650 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
10-27 12:37:59.652 18332-18332/com.threebytes.callservicesample W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
10-27 12:37:59.652 18332-18332/com.threebytes.callservicesample W/System.err: 	... 12 more
10-27 12:39:03.234 18332-18332/com.threebytes.callservicesample W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
10-27 12:52:23.054 18332-18332/com.threebytes.callservicesample W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
10-27 12:52:25.467 18332-18332/com.threebytes.callservicesample W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
10-27 12:52:25.469 18332-18332/com.threebytes.callservicesample W/IInputConnectionWrapper: finishComposingText on inactive InputConnection

**Comment by alispoject** [comment]
please help mi to solve this

**Comment by 3bytessolutions** [comment]
@alispoject @vigneshwarants your client is not authorised to call our backend. you will need to send your client details, go through README for more details.

**Comment by smdeveloper12** [comment]
**## Facing issue in Fail Registration SH1 key pacakge name all proper set so why this type issue face please guide...**

02-19 16:51:01.504 30963-30963/com.example.smtc.videocallsm W/System.err: com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAuthIOException
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:286)
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.threebytes.callapi.z.a(Unknown Source)
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.threebytes.callapi.z.doInBackground(Unknown Source)
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-19 16:51:01.524 30963-30963/com.example.smtc.videocallsm W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at java.lang.Thread.run(Thread.java:841)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err: Caused by: com.google.android.gms.auth.GoogleAuthException: INVALID_AUDIENCE
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.android.gms.auth.zze.zzac(Unknown Source)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.android.gms.auth.zzd.zza(Unknown Source)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.android.gms.auth.zzd.zzb(Unknown Source)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.android.gms.auth.zzd.getToken(Unknown Source)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.android.gms.auth.zzd.getToken(Unknown Source)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.android.gms.auth.zzd.getToken(Unknown Source)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
02-19 16:51:01.534 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
02-19 16:51:01.544 30963-30963/com.example.smtc.videocallsm W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
